#!/usr/bin/env python
from os import system as do, path
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--file', type=str, required=True, help='The path to file to compile')
args = parser.parse_args()

if "__main__" == __name__:
    file_path = args.file
    file_name = ".".join(path.basename(args.file).split(".")[:-1])

    do(f"g++ -o {file_name} {file_path} -I src/include -lboost_system -lfmt")
    do(f"mv ./* ./out")